# Config file for automatic testing at travis-ci.com

language: python
python:
  - 3.9
  - 3.8
  - 3.7
  - 3.6

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U pip tox-travis

# Command to run tests, e.g. python setup.py test
script: tox

# Command to run before deploy
before_deploy:
  - pip install -U pip
  - pip install -r requirements_dev.txt
  - make docs

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: docs/_build/html
    on:
      all_branches: true

  # Assuming you have installed the travis-ci CLI tool, after you
  # create the Github repo and add it to Travis, run the
  # following command to finish PyPI deployment setup:
  # $ travis encrypt --add deploy.password
  - provider: pypi
    distributions: sdist bdist_wheel
    user: __token__
    password:
      secure: MLQvdq+YcUoN6MTsnwxJ5xqC2PuGCOe1grDbGkEoLCYUGHVybbpqjxBa8UNYMm0D4eVND4hoUYQOAyYK8E1J0lgmY/ousaGHanoWqxqYr9ZMfJ/wIRqfGxfpfLI1XeIHV4yL4C8wWEiIFuyECx7VfMIEi3wwVWd7dxa8mx2MVRWWHNWVeMo27qfDAiXlYQ9VZRbgQHZzfOYI9Po8i9nOubZi9vb1Kf2po2z4WXVl6GQlLFvudhwiz925XyKmcf9xCxMs+ALb00LUKREaj0vVtoYSm5+ppkLVOsrb6tF6LO+uKtPImCdtMv4SHSsImO8iQF7nZPBUOnRtFosB8jAIBLndWBBlCN1Xq20r0g0xf/xCx0RITK4oHEUeea2FfaftmV8MOG91Ns+xaYi//SpFNM0vDYHeUGXaNBCuvuN6lb5bep8trzmHRHDH27HISxXfP68mCj2o50hmIIOcupKNZYzQ7JdiExMO4Thn83YMkC1Z+oFJ/oCmYYRyTylR5pHBYvN2d/jbiQrh6XvH01dr8dxc1WZEjbdPYToq5xUVDTqhPE5FwfMxwkorITXH4FgJG05FOEfS/eo+M0mbes5CZ0Tq9MF1H7+P3GLdYQPp5BrsnuhwymIOj7/naOGB2X2lv0uUq79xd+WQ1/9NnTIMzDId25aF5A+H49LjFHMrNOA=
    on:
      tags: true
      repo: accelbyte/iam-python-sdk
      python: 3.8
